### ISSUE TITLE
Issue for Images to be used at the Wiki

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet-architecture/eShopModernizing#1]
![kubectl-get-nodes](https://user-images.githubusercontent.com/1712635/30344662-1301075c-97b7-11e7-93c4-aa7f8c7cc251.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30345114-d232ae04-97b8-11e7-9b33-fe7345ef6975.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30345183-088e05e8-97b9-11e7-85f6-9087108e61d2.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30345811-6cf101f0-97bb-11e7-8e12-f97d9e3870c5.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30345958-02a94b62-97bc-11e7-8bba-c1da60856594.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30346103-8433e4ee-97bc-11e7-83f2-3345b383c9cf.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30346438-935badd4-97bd-11e7-866d-667877dfe30f.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30346477-ae668b76-97bd-11e7-95f1-459eda578ba1.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30346486-bba0075e-97bd-11e7-9d77-84175cd23673.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30346506-cb351db2-97bd-11e7-90f6-9c8196c93acc.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30353284-d86d8afc-97d9-11e7-8cd5-276dbca82ce3.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30354184-db7f1098-97df-11e7-8e7b-c18c67b8ba2a.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30354210-0638f3b2-97e0-11e7-82c5-df18197ccdbd.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30354850-1905b882-97e4-11e7-9620-ce0f25e5eb5f.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30395587-82d445b6-987b-11e7-9ef7-4a1fd0d25df2.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30396175-aa5f1942-987d-11e7-89a6-aeead7001c42.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30396197-b9d4e0be-987d-11e7-9e76-e982ab184e54.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30396480-99d5cf20-987e-11e7-984d-4ddf5244f516.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30396518-bfafaae0-987e-11e7-8473-9cd08d32d80d.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30396561-e2fe2044-987e-11e7-9742-3f6a48c3ddde.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30400808-faffa13c-988c-11e7-97e4-5b3467a903a5.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30401504-620aca58-988f-11e7-8791-201cbafaa6db.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30402676-70f66fc8-9893-11e7-8852-f56ca4c1d474.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30406957-3215bc20-98aa-11e7-8602-5cdae6f7e523.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30406974-5238cc04-98aa-11e7-9bdb-0a3be3a9e0af.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30406999-6d125cc0-98aa-11e7-8681-a6c90a77d6a9.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30407011-8a275db0-98aa-11e7-9b49-8300f1a43464.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30407029-ab66a8d2-98aa-11e7-8e5a-c1ced1834745.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30407087-13c69e14-98ab-11e7-991d-b19198602e74.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30407156-6d860890-98ab-11e7-9083-8fd33209efcd.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30407204-bc6f1a28-98ab-11e7-90c4-1c4f780a0cbe.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30407430-06383b20-98ad-11e7-8c17-085b7411bfb2.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30407695-a16a706c-98ae-11e7-81df-caeb2b05e421.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30407748-f7d7bcfc-98ae-11e7-8301-a987be182611.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30407784-3fc413ee-98af-11e7-84e9-4a76b7cf731d.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30407806-6d4646ca-98af-11e7-91e2-bd5ba1983e8b.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30407870-e7bc6bbe-98af-11e7-90fb-79d9386d68e5.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30407887-04be8e68-98b0-11e7-8d0c-7f757826523c.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30407969-b918d788-98b0-11e7-916b-b34dc4beb401.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30407982-ceb680b8-98b0-11e7-90f3-d472bf41947b.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30408023-04a947f0-98b1-11e7-9717-62b34d393bc5.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30408042-24e39b9c-98b1-11e7-97a7-5d47be91635e.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30408054-42458754-98b1-11e7-9780-a42646e0803d.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30408234-4cc35c50-98b2-11e7-9af4-e961e3f57400.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30408265-68136194-98b2-11e7-9be8-f39852c9d305.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30443299-e46d97ce-9933-11e7-9005-43ae36c96dc2.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30446343-b62df84a-993d-11e7-8c53-9f0a4b788d4c.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30459069-36dfec12-9963-11e7-8d5e-b32529ab9826.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30459153-c24dfa8c-9963-11e7-92ec-95b151d12c73.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30459334-e1b02412-9964-11e7-8bf1-a14b39f66e07.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30460079-70fe03a6-9969-11e7-87d8-a68904885927.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30460282-bdab5d88-996a-11e7-8e9c-553c62b1cf4c.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30460401-9b1850c2-996b-11e7-8780-e5a5975bab36.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30460923-00a9c9cc-996f-11e7-8155-ae1511ca8b35.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30460995-74b1ee80-996f-11e7-833a-d96e42edd136.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30461319-6611b5a6-9972-11e7-81d0-9d99e523257d.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30462085-1e07fb8e-9978-11e7-9b16-fc272a0f04ae.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30462125-6b6362ec-9978-11e7-91a0-cfbad2c3bc43.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30514317-2f4b90cc-9ac7-11e7-8ebc-d58b52823528.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30514707-3c54c786-9acf-11e7-824d-e6c10139dece.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30515157-98375750-9ad7-11e7-9b80-1d90a13f655c.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30515188-0f9a9faa-9ad8-11e7-9013-7d1dbd31ad6f.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30515271-53ba04b8-9ad9-11e7-9f33-a52629adbc5d.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30515279-960b96e2-9ad9-11e7-9e80-89f0b9e082d2.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30525511-d98ee354-9bbc-11e7-9989-1645d4110a90.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30525537-3970929a-9bbd-11e7-9710-4ec01042553a.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30525564-d6684c82-9bbd-11e7-8513-ae0803529fe5.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30527536-c98c2daa-9bde-11e7-8406-3d15515bc73a.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30527551-12a5e8aa-9bdf-11e7-8c6c-269b3dd34b9a.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30527624-a7dc312c-9bdf-11e7-9d3b-77f3c968a373.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30527667-f8972ed2-9bdf-11e7-9b97-79a9ad6946a3.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30572704-3280de9e-9ca4-11e7-8527-b4d45f4acdf6.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30777199-499fbacc-a06a-11e7-88ac-8928a6f269ec.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30787059-bd74a8ba-a135-11e7-8a1d-7eb580f0bd56.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/30787073-f2f5e364-a135-11e7-918a-1472b4f3ee93.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/31475227-74e43246-aeb4-11e7-8dba-44da5fc3874b.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/38158420-f9b24c5a-3448-11e8-8c1f-e5119bd4119c.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/38328528-01ad06ce-3800-11e8-94c4-d775eb1de47f.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/38329793-b641ee1c-3803-11e8-8f61-86c778571f82.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/38333879-aff52212-380e-11e8-925a-5647117929ea.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/38333956-e77845de-380e-11e8-8177-fc7b94a0bf9f.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/38335264-9eef63b6-3812-11e8-9d97-5f5bf598f846.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/38335690-081e95fe-3814-11e8-8cda-278a727425ff.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/38338301-e1d19eaa-381d-11e8-969b-3b44bc78f703.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/38338670-59b09c86-381f-11e8-896e-e6480835da99.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/38395601-9258dd0e-38e8-11e8-8b42-cafff5f93c57.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/38648889-75bd77da-3da8-11e8-8f6d-7e45a30af502.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/38649970-32243986-3dae-11e8-9fce-37128758bfff.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/38650866-17f7d810-3db3-11e8-996b-27d918b7f7a7.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/38651105-3d7261f4-3db4-11e8-8721-7d3cbd8ca324.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/38697246-4b74ce44-3e46-11e8-9939-57519b95e701.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/38697507-1d826338-3e47-11e8-8ab7-bf9e25ddfa0a.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/38698433-dca54a76-3e49-11e8-91c4-fc0dda628ebb.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/38698749-f5db875c-3e4a-11e8-9718-34eef9f230b3.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/38698893-60db724c-3e4b-11e8-9c1c-3d270d44069e.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/38699524-1971b112-3e4d-11e8-8e8b-25e6b4ff10d8.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/38699696-998a7d34-3e4d-11e8-9cee-63914686f9ae.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/38701251-3dbebbfa-3e52-11e8-8271-c2bb8cc91d27.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/38711565-4aeef5c8-3e7b-11e8-865e-5afe698c4048.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/38711588-6c0d20cc-3e7b-11e8-8771-864d74d4fb7a.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/38892978-b5b1cf32-423d-11e8-8876-ccc298d1800f.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/38893504-537a24ac-423f-11e8-98c4-54516a0b4813.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/38949583-a2c11ba2-42f7-11e8-9c10-b74f2a005186.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/38950108-56b355ac-42f9-11e8-89ed-fae5a221a75d.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/39013031-fb72cce0-43ca-11e8-9043-daaf9fcdf33e.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/39013199-89e26abc-43cb-11e8-925f-b54e25234f3f.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/39013955-d18d3200-43cd-11e8-9180-5d9ea0fdf8c8.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/39015115-3c6b6058-43d1-11e8-9429-44115989f018.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/39015430-2ed56ee2-43d2-11e8-9e17-be5af169ce1f.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/39272768-b92459a0-4891-11e8-9f4b-c4709a668095.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/39273098-b64fb304-4892-11e8-962d-288b6b63d8e9.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/39273181-f8f0f876-4892-11e8-8edb-5e6993bec8df.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/39451831-efb91ec8-4c84-11e8-8354-37df8c41889d.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/39452019-9bc89522-4c85-11e8-8204-f639aa4be992.png)

**Comment by CESARDELATORRE** [comment]
![image](https://user-images.githubusercontent.com/1712635/39775972-4eb63e1c-52b4-11e8-85b8-f5b60e3bad79.png)

**Comment by efleming18** [comment]
![NewSetupStep1](https://user-images.githubusercontent.com/1899987/57740631-cd165980-7686-11e9-812f-2f3b7cb6fd13.PNG)

**Comment by efleming18** [comment]
![NewDockerStep](https://user-images.githubusercontent.com/1899987/57740651-e0292980-7686-11e9-9197-b7f02b964b74.PNG)

**Comment by efleming18** [comment]
![image](https://user-images.githubusercontent.com/1899987/57740873-f84d7880-7687-11e9-853e-ddc92feca752.png)

**Comment by efleming18** [comment]
![image](https://user-images.githubusercontent.com/1899987/57740909-1c10be80-7688-11e9-9bbf-9588662ceeac.png)

**Comment by efleming18** [comment]
![image](https://user-images.githubusercontent.com/1899987/57741218-c1786200-7689-11e9-82e2-9619578d047f.png)

**Comment by efleming18** [comment]
![image](https://user-images.githubusercontent.com/1899987/57741254-02707680-768a-11e9-9ebd-7cca36472226.png)

**Comment by efleming18** [comment]
![image](https://user-images.githubusercontent.com/1899987/57741312-49f70280-768a-11e9-9091-aaf9064b09cc.png)

**Comment by ardalis** [comment]
![image](https://user-images.githubusercontent.com/782127/58737306-052fd300-83cf-11e9-8581-24ce6829a65c.png)

**Comment by ardalis** [comment]
![image](https://user-images.githubusercontent.com/782127/58737392-563fc700-83cf-11e9-85dc-0c9af3fd7a59.png)

**Comment by ardalis** [comment]
![image](https://user-images.githubusercontent.com/782127/58737894-5a6ce400-83d1-11e9-992d-2cbcea6192f5.png)

**Comment by ardalis** [comment]
![image](https://user-images.githubusercontent.com/782127/58737945-94d68100-83d1-11e9-8300-a5223ce03ea8.png)

**Comment by efleming18** [comment]
![UpdateKubernetesDeploymentInACS](https://user-images.githubusercontent.com/1899987/61177768-7526a100-a5aa-11e9-8279-bdfba19e1335.png)

**Comment by ardalis** [comment]
![image](https://user-images.githubusercontent.com/782127/146063397-15a72a7f-402d-44ff-a823-e6adbf557cab.png)
