### ISSUE TITLE
at wiki , Pls update  for "09. How to add authentication authorization with Azure Active Directory"

### ISSUE THREAD

**Issue by tutul2010** [dotnet-architecture/eShopModernizing#100]
Hi Team,

Existing Images are broken and ADD app registration are also changed now (in 2023 year) for below wiki sections 

_Wiki **Navigation** -_
"09. How to add authentication authorization with Azure Active Directory(https://github.com/dotnet-architecture/eShopModernizing/wiki/09.-How-to-add-authentication-authorization-with-Azure-Active-Directory)" section. 

Please, update above wiki page for better help and referencing.

Thanks,

**Comment by jamesmontemagno** [comment]
fixed up
