### ISSUE TITLE
Building the Legacy MVC/WebForms projects fails due to missing Roslyn compiler

### ISSUE THREAD

**Issue by ross-p-smith** [dotnet-architecture/eShopModernizing#18]
When trying to debug these two solutions on Windows 10, Visual Studio 2017 you will come across the following error: - https://stackoverflow.com/questions/32780315/could-not-find-a-part-of-the-path-bin-roslyn-csc-exe

It is solved by running this in teh PackageManager
Update-Package Microsoft.CodeDom.Providers.DotNetCompilerPlatform -r

**Comment by efleming18** [comment]
@ross-p-smith I had a PR merged that updated all of the NuGet packages, as well as targeting 4.7.2 so this should be resolved if you get latest. If you get latest, you may have to clear your bin folder out and rebuild since there were many changes. It all worked for me!

**Comment by spottedmahn** [comment]
`Update-Package Microsoft.CodeDom.Providers.DotNetCompilerPlatform -r` fixed it for me too, thanks @ross-p-smith 👍

**Comment by efleming18** [comment]
Interesting @spottedmahn - I tried again and was unable to get the error. This is the [PR](https://github.com/dotnet-architecture/eShopModernizing/pull/17) that it was updated in.

**Comment by spottedmahn** [comment]
Yes, very interesting.  Wonder what would happen if you tried a fresh clone?

Here's the changes I see that I think fixed it on my local system:

![image](https://user-images.githubusercontent.com/14079228/55445862-4c464700-558b-11e9-9b04-a43f1e957505.png)

In the PR, I see [packages.config](https://github.com/dotnet-architecture/eShopModernizing/pull/17/files?file-filters%5B%5D=.config#diff-31cdd1f22c702ab350a78d7dc612dfec) was updated but under: `eShopLegacyMVC/packages.config`.

I'm guessing `eShopModernizedMVC/packages.config` needs to be updated?

You would know more then me though 😊

**Comment by ardalis** [comment]
I ran into this issue with a fresh clone as well. This SO question had a fix that worked:
https://stackoverflow.com/questions/32780315/could-not-find-a-part-of-the-path-bin-roslyn-csc-exe

I'm adding it in a separate PR.

**Comment by ardalis** [comment]
I just got this error again on another machine. This time I fixed it with this:
https://stackoverflow.com/a/34391473/13729

Specifically, run this in Package manager console:
Update-Package Microsoft.CodeDom.Providers.DotNetCompilerPlatform -r
