### ISSUE TITLE
First time deploying a SQL Container to a Service Fabric cluster takes long and timeout errors appear

### ISSUE THREAD

**Issue by CESARDELATORRE** [dotnet-architecture/eShopModernizing#2]
The first time you deploy a SQL Container to a Service Fabric cluster it will take long and timeout errors, like the ones below,  appear in SF Explorer.

You'll need to wait for quite some time the first time until the SQL Server Docker image (it is large) gets pulled from Docker Hub and everything is installed.

![image](https://user-images.githubusercontent.com/1712635/30514599-25e3b9e6-9acd-11e7-9122-548eaf7e23dd.png)

In the case experienced, when deployed the SQL Server container in the first place, it took almost 1h for the Service Fabric to get the SQL Server container due to initial timeouts. But, if you just wait, you should get it running finally like here:

![image](https://user-images.githubusercontent.com/1712635/30515157-98375750-9ad7-11e7-9b80-1d90a13f655c.png)

After that, you can connect to the SQL Container from SQL Server Management Studio, provided that you opened the needed port in the SF cluster ant the SF SQL service enpoint at the ServiceManifest.xml, so you can see the SQL Server like here:

![image](https://user-images.githubusercontent.com/1712635/30515188-0f9a9faa-9ad8-11e7-9013-7d1dbd31ad6f.png)

**Comment by lfgalvao89** [comment]
Hey man, do you have any tutorial on how to build and deploy an SQL Server and/or a MongoDB server to service fabric using containers?
I saw a ton of resources on the internet, however I still can't figure out what I'm doing wrong.
I get the image link from hub.docker.com, assembly the folder structure, deploy and still can't connect. 
I've tried all kinds of port settings on service and application manifest, and still no success.

**Comment by CESARDELATORRE** [comment]
@lfgalvao89 
You have our SF deployment scripts including the SQL and MongoDB containers, here:
https://github.com/dotnet-architecture/eShopModernizing/tree/master/ServiceFabric

Also, the setup procedure for SF, including those containers, is here:
https://github.com/dotnet-architecture/eShopModernizing/wiki/05.-How-to-deploy-your-Windows-Containers-based-apps-into-Azure-Service-Fabric-(Including-CI-CD)

Additional SF deployments for the microservices application (eShopOnContainers instead of eShopModernizing) is here:
https://github.com/dotnet-architecture/eShopOnContainers/wiki/11.-Setting-the-solution-up-in-Service-Fabric

Hope it helps. :)

**Comment by efleming18** [comment]
Closing for now. We can reopen if anyone has further questions.
