### ISSUE TITLE
How to add Certificate pfx to Docker Image?

### ISSUE THREAD

**Issue by abhishek-raj** [dotnet-architecture/eShopModernizing#23]
I want to add an certificate to my Docker Image which authenticates with Azure Keyvault to get some secret values. I imported the certificate using DockerFile into the LocalMachine/My but my dotnet MVC application is not able to access it. It shows a `Keyset does not exist` error. The problem is probably of permissions as the IIS runs with some other Service Account which might not have access to the Private Machine Key.

Is there a way to add the Certificate to the Docker Image?

**Comment by efleming18** [comment]
Hey @abhishek-raj - since this issue has been open for a while, I just wanted to check if this was still an issue for you before taking a look in to it?

**Comment by abhishek-raj** [comment]
I was able to solve it by giving access to the certificate private key. I used the script from here:
https://stackoverflow.com/questions/40046916/how-to-grant-permission-to-user-on-certificate-private-key-using-powershell

Copying the scipt here just in case:
```
param(
    [string]$userName,
    [string]$permission,
    [string]$certStoreLocation,
    [string]$certThumbprint
);
# check if certificate is already installed
$certificateInstalled = Get-ChildItem cert:$certStoreLocation | Where thumbprint -eq $certThumbprint

# download & install only if certificate is not already installed on machine
if ($certificateInstalled -eq $null)
{
    $message="Certificate with thumbprint:"+$certThumbprint+" does not exist at "+$certStoreLocation
    Write-Host $message -ForegroundColor Red
    exit 1;
}else
{
    try
    {
        $rule = new-object security.accesscontrol.filesystemaccessrule $userName, $permission, allow
        $root = "c:\programdata\microsoft\crypto\rsa\machinekeys"
        $l = ls Cert:$certStoreLocation
        $l = $l |? {$_.thumbprint -like $certThumbprint}
        $l |%{
            $keyname = $_.privatekey.cspkeycontainerinfo.uniquekeycontainername
            $p = [io.path]::combine($root, $keyname)
            if ([io.file]::exists($p))
            {
                $acl = get-acl -path $p
                $acl.addaccessrule($rule)
                echo $p
                set-acl $p $acl
            }
        }
    }
    catch 
    {
        Write-Host "Caught an exception:" -ForegroundColor Red
        Write-Host "$($_.Exception)" -ForegroundColor Red
        exit 1;
    }    
}

exit $LASTEXITCODE
```
I ran the script with user name: 'IIS APPPOOL\DefaultAppPool'
```
changeperm.ps1 -userName 'IIS APPPOOL\DefaultAppPool' -permission read -certStoreLocation \LocalMachine\My -certThumbprint 1fb7603985a8a11d3e85abee194697e9784a253
```
Basically the name of the Service Account which runs the IIS in the default docker image is 'IIS APPPOOL\DefaultAppPool' which needs to have access to the certificate.

**Comment by efleming18** [comment]
Thanks for the information @abhishek-raj! I'm glad you were able to get it figured out! :)
