### ISSUE TITLE
Unable to start debugging on the web server. The remote server returned an error: (403) Forbidden

### ISSUE THREAD

**Issue by spottedmahn** [dotnet-architecture/eShopModernizing#24]
I'm trying to follow the ["02. How to containerize the .NET Framework web apps with Windows Containers and Docker"](https://github.com/dotnet-architecture/eShopModernizing/wiki/02.-How-to-containerize-the-.NET-Framework-web-apps-with-Windows-Containers-and-Docker) demo and I'm getting the following error on F5 of the docker-compose project:

![image](https://user-images.githubusercontent.com/14079228/55360560-c18a1d00-54a2-11e9-9cef-29c08552353b.png)

### Docker Debug Window:

> ========== Debugging ==========
> docker ps --filter "status=running" --filter "name=dockercompose12807194206851661871_eshop.modernized.mvc_" --format {{.ID}} -n 1
> 0c0c4e368750
> docker inspect --format="{{range .NetworkSettings.Networks}}{{.IPAddress}} {{end}}" 0c0c4e368750
> 172.19.106.56 
> docker exec 0c0c4e368750 cmd /c "C:\Windows\System32\inetsrv\appcmd.exe set config -section:system.applicationHost/applicationPools /[name='DefaultAppPool'].processModel.identityType:LocalSystem /commit:apphost & C:\Windows\System32\inetsrv\appcmd.exe set config -section:system.webServer/security/authentication/anonymousAuthentication /userName: /commit:apphost"
> Applied configuration changes to section "system.applicationHost/applicationPools" for "MACHINE/WEBROOT/APPHOST" at configuration commit path "MACHINE/WEBROOT/APPHOST"
> Applied configuration changes to section "system.webServer/security/authentication/anonymousAuthentication" for "MACHINE/WEBROOT/APPHOST" at configuration commit path "MACHINE/WEBROOT/APPHOST"

VS 2017 (15.9.10)

**Comment by biste5** [comment]
I had the same. For me the fix was to change the target FX for the MVC Web App from 4.7.2 to 4.7
Seems like the docker image used to run the application doesn't have 4.7.2!

HTH

**Comment by nilavanrajamani** [comment]
For me setting <compilation debug="true"> from false in web.config resolved the issue.

**Comment by nilavanrajamani** [comment]
For me setting configuration/system.web/compilation[debug='true'] from false solved the issue
