### ISSUE TITLE
provide a documentation for how to install   Kubernetes  feature at Windows 2016 with hyperv with  Docker at local dev system .

### ISSUE THREAD

**Issue by tutul2010** [dotnet-architecture/eShopModernizing#46]
HI Team,
Pls ,help me to provide a documentation for how to install   Kubernetes  feature at Windows 2016 with hyperv with  Docker local system.
I am using above for dev environment.

Thanks,
Tutul

**Comment by efleming18** [comment]
Hey @tutul2010 - were you able to find an answer to this? [This doc](https://docs.microsoft.com/en-us/virtualization/windowscontainers/kubernetes/getting-started-kubernetes-windows) deals with Kubernetes on Windows but I believe it's for Windows Server 2019.

**Comment by tutul2010** [comment]
Thanks @efleming18 .
It is for windows server 2019 -OS .. i am looking for on windows server 2016 like OS.

Regards,

**Comment by sughosneo** [comment]
Hi @tutul2010 , you can find more details in this [intro-windows-in-kubernetes](https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/) documentation. 

I am closing this issue as of now. Please feel reopen it if you have any further question. 

Thank you.
