### ISSUE TITLE
Getting issue "A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections" after running the mvc web app after deployment to aci

### ISSUE THREAD

**Issue by vinitgadre** [dotnet-architecture/eShopModernizing#47]
Getting issue "A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections"
I followed same steps as in article to deploy the images to ACI

**Comment by efleming18** [comment]
Hey @vinitgadre - are you able to connect to it through SSMS? I just want to rule out using the incorrect connection string/credentials in the application. An easy way to test that is to make sure you can connect to the database through SSMS to verify username, password, connection string.

**Comment by sughosneo** [comment]
Hi @vinitgadre , I am closing this issue as of now as it's inactive for sometime now. Please feel free to reopen it, if you have any further questions. 

Thank you.
