### ISSUE TITLE
Update eShopWinForms sample to target netcoreapp3.1 instead of netcoreapp3.0

### ISSUE THREAD

**Issue by OliaG** [dotnet-architecture/eShopModernizing#48]
Update <TargetFramework>netcoreapp3.0</TargetFramework> to <TargetFramework>netcoreapp3.1</TargetFramework> in https://github.com/dotnet-architecture/eShopModernizing/blob/master/eShopModernizedNTier/src/eShopWinForms/eShopWinForms.csproj

**Comment by efleming18** [comment]
Resolved via the attached PR
