### ISSUE TITLE
eShopLegacyWebForms does not compile

### ISSUE THREAD

**Issue by PRudykIteo** [dotnet-architecture/eShopModernizing#57]
I found this project during MS Learn Tutorial: https://docs.microsoft.com/pl-pl/learn/modules/aspnet-session/
During exercise I was told to download project from this repository. As stated in instructions, VS asked me to install additional components. During all this time, solution did not compile.
Unfortunately VS provided only ambiguous messages about missing or conflicting packages without any error code. However, after some research, I was able to fix this error by downgrading log4net nuget package to 2.0.8.0.
I can prepare a pull request if needed.

**Comment by anirugu** [comment]
same here,  tried to build on 2 machine. installed the .net 4.7.2 which is missing on 1 machine. doesn't work on any of both. 

Can someone look into this matter.

**Comment by sughosneo** [comment]
Hi @PRudykIteo / @anirugu - thank you for reaching out and reporting this behavior. Will test and update.

**Comment by sughosneo** [comment]
Hey @PRudykIteo, yes, your analysis was correct. 👍 There is some issue with the `log4net` package. Actually, within the `src\eShopLegacyWebForms\eShopLegacyWebForms.csproj` file package is still pointing to the old version `2.0.8`. 
And that's the reason if you downgrade the `log4net`, then the project gets build successfully. My suggestion would be, let's update the solution with `log4net version as `2.0.10`. 

You could submit a PR with the changes. We will be happy to review and merge the changes with the `main` branch.

Thank you.

**Comment by sughosneo** [comment]
This issue has been fixed. So closing it. Thank you.
