### ISSUE TITLE
Docker Image Build Issue with VSTS

### ISSUE THREAD

**Issue by denhsu** [dotnet-architecture/eShopModernizing#6]
Hi,
I am trying to build docker image with VSTS by following the steps on  Scenario C: Deploying from VSTS CD pipeline to an Azure VM using the Docker Tasks in VSTS in "https://github.com/dotnet-architecture/eShopModernizing/wiki/03.-How-to-deploy-your-Windows-Containers-based-app-into-Azure-VMs-(Including-CI-CD)".

I keep getting below error.  does "obj\Docker\publish" suppose to exist?  I am using hosted VS2017 agent to build.  Do i need to create my own private docker build agent?

--------------------
2018-01-05T19:22:22.8988540Z Step 4/4 : COPY ${source:-obj/Docker/publish} .
2018-01-05T19:22:23.6913778Z COPY failed: GetFileAttributesEx \\?\C:\Windows\TEMP\docker-builder239959299\obj\Docker\publish: The system cannot find the path specified.
2018-01-05T19:22:34.4747563Z ##[error]C:\Program Files\Docker\docker.exe failed with return code: 1

Any help is appreciated!

Thanks,
Dennis

**Comment by CESARDELATORRE** [comment]
No, you don't need to create a private docker build agent.
I think that was a bug I reported to the VSTS Docker Task team.
You have 2 workarounds, if your issue is the same:
1. Workaround 1 
When specifying the docker-compose.**override** file, specify a relative path instead a full path to the file.

2. Workaround 2
Use the older/deprecated Docker-compose task.

Please, confirm if that was the issue.

**Comment by denhsu** [comment]
Thanks  @CESARDELATORRE for the quick reply.

I am following your instruction:
Building and pushing the Docker image to a Docker Registry (Docker Hub or Azure Container Registry)

For the CI we have a Build with 4 steps. The first two are standard in majority of builds, a restore for the Nuget packages and a build of the .Net project.

The third step is 'Build the image' using the docker-compose tool. We only need to pass the docker-compose files as parameters. In the 'Docker Compose File' variable we add our main docker-compose file (in this case 'eShopModernizedMVCSolution/docker-compose.yml'), and in the 'Additional Docker Compose Files' field we add the rest of docker-compose files (in this case only the 'eShopModernizedMVCSolution/docker-compose.override.yml'). If you need any extra tags for the image add them in this step. The 'Action' is 'Build service images'.


1.  I tried exactly same thing, but got the above error.  In VS2017, when I do F5, I can build, run docker image fine, but not in VSTS build definition.

error:
2018-01-05T19:22:22.8988540Z Step 4/4 : COPY ${source:-obj/Docker/publish} .
2018-01-05T19:22:23.6913778Z COPY failed: GetFileAttributesEx \?\C:\Windows\TEMP\docker-builder239959299\obj\Docker\publish: The system cannot find the path specified.
2018-01-05T19:22:34.4747563Z ##[error]C:\Program Files\Docker\docker.exe failed with return code: 1

2. Workaround #2 is gone as [Deprecated] Docker-compose tasks can't be found in VSTS anymore.  I tried both existing Docker and Docker compose tasks, but same results.  

I wonder if you can create a new VSTS build definition using either the existing Docker and Docker compose tasks to build the docker image and you will see the error.

Any info is appreciated!

Thanks!

**Comment by CESARDELATORRE** [comment]
In the 'Additional Docker Compose Files' field where you put the 'eShopModernizedMVCSolution/docker-compose.override.yml' , try changing that path from an absolute path to a relative path.
That is the bug I isolated and reported and I wonder if you are having the same issue.

**Comment by denhsu** [comment]
I tried to run the "docker-compose build" command locally and I see same error message from VSTS.

I think my issue is with the path set in 4th line.

Dockerfile:
FROM microsoft/aspnet:4.7.1-windowsservercore-1709
ARG source
WORKDIR /inetpub/wwwroot
**COPY ${source:-obj/Docker/publish} .**

Error:
PS C:\Users\DH56022\source\repos\ContainerPOC\eShopLegacyMVCSolution> docker-compose build
Building eshoplegacymvc
Step 1/4 : FROM microsoft/aspnet:4.7.1-windowsservercore-1709
 ---> 962fe4c099b1
Step 2/4 : ARG source
 ---> Using cache
 ---> a4d3d9fe28ff
Step 3/4 : WORKDIR /inetpub/wwwroot
 ---> Using cache
 ---> 2e7b93281706
Step 4/4 : COPY ${source:-obj/Docker/publish} .
ERROR: Service 'eshoplegacymvc' failed to build: COPY failed: CreateFile \\?\C:\ProgramData\Docker\tmp\docker-builder024450850\obj\Docker\publish: The system cannot find the file specified.

Thanks!

**Comment by CESARDELATORRE** [comment]
OK, you should have told me that you were trying to deploy your own containers (Windows Containers in this case), not really eShopOnContainers.
We cannot provide support for your own environment/development because of lack of time bandwidth.
In any case, the line  COPY ${source:-obj/Docker/publish} . is trying to copy your compiled .NET application bits from obj/Docker/publish.
Make sure you have the compiled bits in that path, other than that, it logically cannot create the Docker image.

Another solution is to use Docker Multi-Stage builds, so docker itself will compile the .NET bits in the same execution. This is how we're doing now in eShopOnContainers. Look at this dockerfile:
https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Catalog/Catalog.API/Dockerfile
Note that in our case we're using .NET Core, but you are using .NET Framework and Windows Containers.

If you create a new ASP.NET project (traditional .NET Framework and ASP.NET MVC, for instance) with the latest version of Visual Studio 2017 15.5.3 and enable Docker support on it, you can see how it is now using Docker Multi-Stage builds. You can use the same approach.

In any case, I'm closing this issue since it is not related to eShopOnContainers but your own development.

**Comment by denhsu** [comment]
Thanks @CESARDELATORRE You have solved my issue.

I realized i have to build the solution specifically with "Release" configuration, otherwise, the ${source:-obj/Docker/publish} folder won't show up.

Thanks!

**Comment by CESARDELATORRE** [comment]
Glad to help!  👍

**Comment by michaelsrichter** [comment]
@CESARDELATORRE hi, I am having a similar problem trying to build the docker file - every time I try with a docker-compose build command, I get an error like

`ERROR: Service 'eshoplegacymvc' failed to build: COPY failed: CreateFile \\?\C:\ProgramData\Docker\tmp\docker-builder407623176\bin\Release\PublishOutput: The system cannot find the path specified.`

I know that bin\Release\PublishOutput exists. That is a relative path from where my Dockerfile is.  I can't figure out how to solve.

Thanks

**Comment by denhsu** [comment]
@michaelsrichter I had a similar issue.  I couldn't see the folder structure in hosted agent.  I setup a private build agent to run the docker build in VSTS (very easy to setup), so i can see the folder structure easier.  I also need to manually build the VS 2017 solution with "Release" configuration once, then run the docker build in VSTS using my private build agent and everything worked afterwards.   Hope this helps.

Dennis

**Comment by Kalaicompute** [comment]
I have been struggling with this similar issue for few days. I managed to find a way finally. I use ".Net Core" build and publish tasks to publish service into "obj/Docker/publish" folder and then use "Docker Compose" tasks to build and push the images to private container repository.

Kalai

**Comment by willemodendaal** [comment]
@abhayongit Unfortunately that doesn't work for me. I'm still stuck with the weird "programData" path :(

**Comment by abhayongit** [comment]
@willemodendaal <https://github.com/willemodendaal>  -  Could you please
share your DockerFile and what you want to achieve ?

**Comment by amivit** [comment]
Extremely frustrating. Same issue. Azure DevOps with on-premise build agent. Everything is super default. Fresh Server 2016 server, fresh docker-for-windows, fresh ASP.NET Core 2.1 project, simple configuration

```
FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 12073
EXPOSE 44337

FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
COPY ["ACo.API/ACo.API.csproj", "ACo.API/"]
RUN dotnet restore "ACo.API/ACo.API.csproj"
COPY . .
WORKDIR "/src/ACo.API"
RUN dotnet build "ACo.API.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "ACo.API.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "ACo.API.dll"]
``` 

But always getting:

COPY failed: CreateFile \\?\C:\ProgramData\Docker\tmp\docker-builder597994875\ACo.API\ACo.API.csproj: The system cannot find the path specified.

Pretty new to docker so not sure what to try. It works perfectly okay from Visual Studio.

**Comment by abhayongit** [comment]
Go inside ACo.API folder and change the copy command like follwoing

COPY ["./ACo.API.csproj", "."]

**Comment by Mutz2** [comment]
Hi i have similar problem , My docker file is as stated below.

I have docker file and this simulator folder in same location and exe file is in simulator **--> bin --> x64 --> Debug --> simulator.exe**

 I am struggling to copy whole source code and then run my exe app. and this app is .Net framework app built on version 4.6.1. And am i using right image ?

Please suggest me better way of writing Docker file and my app is .Net framework app built on version 4.6.1.

#FROM mcr.microsoft.com/windows/servercore:ltsc2016
FROM mcr.microsoft.com/dotnet/framework/sdk:4.8
WORKDIR /app

COPY simulator .

ENTRYPOINT ["\simulator\bin\x64\Debug\simulator.exe"]
#RUN powershell -Command C:\simulator\bin\x64\Debug\simulator.exe
