### ISSUE TITLE
eShopModerniziMVC and Web Forms also have build errors Log4net 2.08 

### ISSUE THREAD

**Issue by rocketingineer** [dotnet-architecture/eShopModernizing#62]
https://github.com/dotnet-architecture/eShopModernizing/issues/57

Hello The same issue that occurred on the legacy solutions (link above) is happening inside the modernized solutions.

I tried to find the references and modify them to accept the newer version but no dice. I had to downgrade to log4net 2.08 to get the solution file to build. 

Thanks!

**Comment by rocketingineer** [comment]
Whoops link didn't come thru. 

Basically this is a duplicate of issue 57 but the fix needs applied to the other folders. 

Thanks!

**Comment by sughosneo** [comment]
Hi @rocketingineer, thank you for reaching out. 
Could you please take the latest from the `main` branch and try to build the solution again?

**Comment by ShadyNagy** [comment]
Fixed on PR #67

**Comment by ShadyNagy** [comment]
@rocketingineer and @sughosneo 
Fixed on PR #67
