### ISSUE TITLE
03. Publishing your Windows Container images into a Docker Registry - error

### ISSUE THREAD

**Issue by LucaOtto** [dotnet-architecture/eShopModernizing#69]
Followed instructions for this option: https://github.com/dotnet-architecture/eShopModernizing/wiki/03.-Publishing-your-Windows-Container-images-into-a-Docker-Registry#option-1a-straightforward-use-a-single-script-to-build-all-your-apps-and-create-all-the-related-windows-container-images

Build.cmd starts but i receive the below error.

![image](https://user-images.githubusercontent.com/42404744/157274474-52e28351-7311-476e-8f70-8fbabc61fa8a.png)

Only these two images are created:

![image](https://user-images.githubusercontent.com/42404744/157274805-cc1751df-c06c-4630-b697-ea9399636a81.png)

**Comment by erjain** [comment]
Hi @LucaOtto, Thank you for reporting this issue. we have created a PR with an update to the docker file. You can pull these changes, it should work for you. I am closing this issue as of now. Please feel free to reopen if needed.
