### ISSUE TITLE
at wiki , Pls reupload correct images which  are not loading for "Deploying from VSTS CD pipeline to Kubernetes in ACS" sections

### ISSUE THREAD

**Issue by tutul2010** [dotnet-architecture/eShopModernizing#99]
Hi General,

Below navigation wiki page,  images are not loading for "Deploying from VSTS CD pipeline to Kubernetes in ACS" sections as 
![image](https://github.com/dotnet-architecture/eShopModernizing/assets/13733464/fc384820-5d32-48d4-93aa-2b4e15524ede)

Wiki section, **Navigation** -
Looking into "dotnet-architecture/eShopModernizing" github code repo and navigating to "04. How to deploy your Windows Containers based apps into Kubernetes in Azure Container Service (Including CI CD)" wiki section (https://github.com/dotnet-architecture/eShopModernizing/wiki/04.-How-to-deploy-your-Windows-Containers-based-apps-into-Kubernetes-in-Azure-Container-Service-(Including-CI-CD)) 

pls, reupload correct images.

Thanks,

**Comment by jamesmontemagno** [comment]
fixed
